<svg
    {{ $attributes }}
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
>
    <circle
        cx="4"
        cy="7"
        r="2"
        stroke="#000"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
    />
    <circle
        cx="20"
        cy="7"
        r="2"
        stroke="#000"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
    />
    <circle
        cx="20"
        cy="17"
        r="2"
        stroke="#000"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
    />
    <path
        stroke="#000"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M18 7H6M7 7v0a3 3 0 0 1 3 3v5a2 2 0 0 0 2 2h6"
    />
</svg>
