<?php

declare(strict_types=1);

namespace App\Policies;

use App\Models\User;
use Illuminate\Auth\Access\HandlesAuthorization;

/**
 * Generated by Shield, then edited by hand: staff without super admin rights
 * may never change or remove a super admin's account.
 */
class UserPolicy
{
    use HandlesAuthorization;

    public function viewAny(User $authUser): bool
    {
        return $authUser->can('ViewAny:User');
    }

    public function view(User $authUser, User $user): bool
    {
        return $authUser->can('View:User');
    }

    public function create(User $authUser): bool
    {
        return $authUser->can('Create:User');
    }

    public function update(User $authUser, User $user): bool
    {
        return $authUser->can('Update:User') && $this->canManage($authUser, $user);
    }

    public function delete(User $authUser, User $user): bool
    {
        return $authUser->can('Delete:User') && $this->canManage($authUser, $user);
    }

    public function deleteAny(User $authUser): bool
    {
        return $authUser->can('DeleteAny:User');
    }

    public function reorder(User $authUser): bool
    {
        return $authUser->can('Reorder:User');
    }

    protected function canManage(User $authUser, User $user): bool
    {
        return $authUser->isAdmin() || ! $user->isAdmin();
    }
}
